### ISSUE TITLE
ValueError: Normal distribution got invalid scale parameter During .fit() call

### ISSUE THREAD

**Issue by RogerWebb** [google/lightweight_mmm#115]
This is a question related to my attempt to implement the sample presented during PyData 2022 with our own data.  I am able to successfully train the sample data following the process outlined in the talk here:
https://github.com/takechanman1228/mmm_pydata_global_2022/blob/main/simple_end_to_end_demo_pydataglobal.ipynb

When I attempt to reproduce the results with some of our own data, I hit a road-block when attempting to fit the model and searching for this error online doesn't get me any results.  Literally none.  For one of the first times in my career Google actually returned no results for an error, so I was hoping someone on the board here could point me in the right direction, as my knowledge of how these Scalars are supposed to work is limited.
"ValueError: Normal distribution got invalid scale parameter During .fit() call"

I have a Pandas Dataframe with a head() that prints like below.  The only difference I can think of between my model and the sample is the target in the sample was "sales" (ie a currency like the spend) and I'm targeting Conversions, which is a non-currency count of people who converted.

```
  Week_Beginning  Conversions    Social  Audio  Display  Video  Search  Content
0     2019-10-27          0.0   112.000    0.0      0.0    0.0     0.0      0.0
1     2019-11-03          0.0   252.000    0.0      0.0    0.0     0.0      0.0
2     2019-11-10          0.0  1326.000    0.0      0.0    0.0     0.0      0.0
3     2019-11-17          0.0  1700.000    0.0      0.0    0.0     0.0      0.0
4     2019-11-24          0.0  1182.912    0.0      0.0    0.0     0.0      0.0
```

With CustomScalars defined thus:
```python
media_scaler = preprocessing.CustomScaler(divide_operation=jnp.mean)
target_scaler = preprocessing.CustomScaler(divide_operation=jnp.mean)
cost_scaler = preprocessing.CustomScaler(divide_operation=jnp.mean, multiply_by=0.15)
```

With a LightweightMMM model instantiated like so:
```python
mmm = lightweight_mmm.LightweightMMM(model_name="hill_adstock")
mmm.fit(
    media=media_data_train,
    media_prior=costs,
    target=target_train,
    number_warmup=number_warmup,
    number_samples=number_samples,
    media_names = mdsp_cols,
    seed=SEED)
```

and get the following traceback:

```sh
Traceback (most recent call last):
  File "data.py", line 97, in <module>
    mmm.fit(
  File "/usr/local/lib/python3.8/dist-packages/lightweight_mmm/lightweight_mmm.py", line 362, in fit
    mcmc.run(
  File "/usr/local/lib/python3.8/dist-packages/numpyro/infer/mcmc.py", line 597, in run
    states, last_state = _laxmap(partial_map_fn, map_args)
  File "/usr/local/lib/python3.8/dist-packages/numpyro/infer/mcmc.py", line 160, in _laxmap
    ys.append(f(x))
  File "/usr/local/lib/python3.8/dist-packages/numpyro/infer/mcmc.py", line 381, in _single_chain_mcmc
    init_state = self.sampler.init(
  File "/usr/local/lib/python3.8/dist-packages/numpyro/infer/hmc.py", line 706, in init
    init_params = self._init_state(
  File "/usr/local/lib/python3.8/dist-packages/numpyro/infer/hmc.py", line 652, in _init_state
    init_params, potential_fn, postprocess_fn, model_trace = initialize_model(
  File "/usr/local/lib/python3.8/dist-packages/numpyro/infer/util.py", line 676, in initialize_model
    substituted_model(*model_args, **model_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lightweight_mmm/models.py", line 350, in media_mix_model
    fn=dist.HalfNormal(scale=media_prior))
  File "/usr/local/lib/python3.8/dist-packages/numpyro/distributions/distribution.py", line 99, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/numpyro/distributions/continuous.py", line 465, in __init__
    self._normal = Normal(0.0, scale)
  File "/usr/local/lib/python3.8/dist-packages/numpyro/distributions/distribution.py", line 99, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/numpyro/distributions/continuous.py", line 1701, in __init__
    super(Normal, self).__init__(
  File "/usr/local/lib/python3.8/dist-packages/numpyro/distributions/distribution.py", line 177, in __init__
    raise ValueError(
ValueError: Normal distribution got invalid scale parameter.
```

Any help debugging would be most appreciated.

**Comment by michevan** [comment]
Hi Roger, thanks a lot for reaching out! It looks like the issue is with the media priors you're passing to the fit() method. Can you check if any of those priors (the "costs" from the media_prior=costs line in the fit() command) are zero or negative? 

If so, this is causing your issue; the values you pass to the media priors need to be positive numbers!

**Comment by RogerWebb** [comment]
I'll add some sanity checking for my modeling code, but it might be worth wrapping that exception with one that describes this particular issue.  If it's something your team is down to take on, then fantastic.  I'm not flush with time, but have a couple weeks vacation coming up, so if it's something that's not likely to get attention, I can check back and see about dropping a PR if I get some time to crack on it.

**Comment by michevan** [comment]
Thanks a lot for the update and the kind offer, and we do appreciate PRs! For this one in particular though we're actually actively developing it, along with some other guardrails, and it should be online in the public version next week :)
