### ISSUE TITLE
windows 11 installation gives error

### ISSUE THREAD

**Issue by Sandy4321** [google/lightweight_mmm#199]
windows 11 installation gives error
![image](https://user-images.githubusercontent.com/11426119/232155059-0644134f-fa50-492c-a716-1dad3cd4a48f.png)
Requirement already satisfied: scipy in c:\my_py_environments\py_env_jan_2023\lib\site-packages (from lightweight_mmm) (1.10.0)
Requirement already satisfied: seaborn in c:\my_py_environments\py_env_jan_2023\lib\site-packages (from lightweight_mmm) (0.12.2)
Collecting sklearn
  Downloading sklearn-0.0.post4.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\cde3\AppData\Local\Temp\pip-install-exa0dl3y\sklearn_6a38347d77ad4c6fa53da7c9a957bcbe\setup.py", line 10, in <module>
          LONG_DESCRIPTION = f.read()
                             ^^^^^^^^
        File "C:\Users\cde3\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by uomodellamansarda** [comment]
Are you using any virtual environment?

**Comment by SchnockNicolas** [comment]
Same here on MacOS (x84)

<img width="864" alt="Capture d’écran 2023-04-22 à 18 07 22" src="https://user-images.githubusercontent.com/17202207/233794941-df34cc1b-fbad-4f4e-9e34-2de5175418c4.png">

using also virtual env

**Comment by Sandy4321** [comment]
yes
